export default {
  callese: require('./callese.mp3'),
  ay_dios_mio_esto_que_es: require('./ay_dios_mio_esto_que_es.mp3'),
  puro_pelao_marica: require('./puro_pelao_marica.mp3'),
  cristo_mete_tu_mano: require('./cristo_mete_tu_mano.mp3'),
  fuerararara: require('./fuerararara.mp3'),
  jopo_que_pea: require('./jopo_que_pea.mp3'),
  el_bochorno: require('./el_bochorno.mp3'),
  se_partio_la_galleta: require('./se_partio_la_galleta.mp3'),
  ya_basta_erda: require('./ya_basta_erda.mp3'),
  imajije: require('./imajije.mp3'),
  que_esperabas: require('./que_esperabas.mp3'),
  no_hablemos_de_eso: require('./no_hablemos_de_eso.mp3'),
  no_se_ernesto: require('./no_se_ernesto.mp3'),
}